platform :ios, '9.0'

use_frameworks!

target 'RUImageCaptureView_Example' do
  pod 'RUImageCaptureView', :path => '../'

  target 'RUImageCaptureView_Tests' do
    inherit! :search_paths

    
  end
end
